### ISSUE TITLE
hope for the release of code and pretrained weight

### ISSUE THREAD

**Issue by Yindong-Zhang** [ZhichengHuang/CMAE#1]
congradulation on the great work, quite interesting for me.
hope for the release of code and pretrained weight.

best wishes

**Comment by ZhichengHuang** [comment]
Thank you for your attention. Recently, I have been busy with another project, and I will release the code and weight as soon as possible.

**Comment by ZhichengHuang** [comment]
@forkbabu I appreciate your interest in our work. After consulting with our co-authors, we decided to open-source the code after receiving feedback from the peer review for the paper. Thank you for your understanding.
