### ISSUE TITLE
Code release ?

### ISSUE THREAD

**Issue by alexcbb** [ZhichengHuang/CMAE#10]
Hello, thank you for your very interesting work. It seems that after more than one year the code is not yet available, is there any update ? I would be very interested to experiment with you model, thank you again !

**Comment by ZhichengHuang** [comment]
Thank you for your attention. Our previous code relied on mmcv. Due to the upgrade of mmcv, some dependent libraries did not match. We have recently upgraded the code to the latest mmengine and will be able to release the code in about a week.
