### ISSUE TITLE
Is ImageNet_train.json and ImageNet_val.json the path of image?

### ISSUE THREAD

**Issue by LOVEOuziyan** [ZhichengHuang/CMAE#11]
I want to know what on earth are the two files"ImageNet_train.json and ImageNet_val.json ".

Is ImageNet_train.json and ImageNet_val.json the path of image?

**Comment by ZhichengHuang** [comment]
Yes, the ImageNet_train.json and ImageNet_val.json files are indeed related to the ImageNet dataset. Each item in these JSON files contains structured data that provides details about the individual images in the dataset. An example of the structure within these files is as follows:
{
  "filename": "n02115641_23115.JPEG",
  "prefix": "train/n02115641",
  "label": 541
}
Besides, you can download the JSON files using the following links:  https://cmae.s3.us-west-1.amazonaws.com/data/ImageNet_train.json and https://cmae.s3.us-west-1.amazonaws.com/data/ImageNet_val.json

**Comment by LOVEOuziyan** [comment]
Thank  you very much! I see.
















At 2024-02-21 17:35:03, "zhicheng" ***@***.***> wrote:

Yes, the ImageNet_train.json and ImageNet_val.json files are indeed related to the ImageNet dataset. Each item in these JSON files contains structured data that provides details about the individual images in the dataset. An example of the structure within these files is as follows:
{
"filename": "n02115641_23115.JPEG",
"prefix": "train/n02115641",
"label": 541
}
Besides, you can download the JSON files using the following links: https://cmae.s3.us-west-1.amazonaws.com/data/ImageNet_train.json and https://cmae.s3.us-west-1.amazonaws.com/data/ImageNet_val.json
