### ISSUE TITLE
Is it possible to pretrain on custom dataset?

### ISSUE THREAD

**Issue by Synnai** [ZhichengHuang/CMAE#15]
Your work is impressive and splendid. Therefore I'm currently interested in deploying your method on domain-specific datasets (which is quite different from ImageNet). Is it possible to pretrain on custom dataset, by just adjusting the structure of my datasets as how you use ImageNet-1k (including generating .json files as well)? Thanks!

**Comment by ZhichengHuang** [comment]
Thank you for your attention to our work. We have not trained on datasets that differ significantly from ImageNet. You only need to adjust the dataset part. Additionally, a very important point is that when you try this, try to maintain a relatively large batch size, such as 4096
