### ISSUE TITLE
What's the output of feature decoder ?

### ISSUE THREAD

**Issue by HuangChiEn** [ZhichengHuang/CMAE#3]
Hello, thanks for releasing this great work.

Recently, we attempt to implement the CMAE according to the paper, if you don't mind to tell me about some crucial detail.
> When i implement the feature decoder, which is similar with the pixel decoder (almost same with MAE decoder, but given the shallow depth(only 2~4 block) ).

However, we're not sure about the output of the feature decoder :
Is the feature decoder *only* output the prediction of masked patchs and conduct the mean-pooling to get the feature representation ? or,  
feature decoder will output *all* prediction of patchs (including the unmasked patchs) and conduct the mean-pooling to get the feature representation ?

Any suggestion will be appreciated!!

**Comment by ZhichengHuang** [comment]
Thank you for your attention. For the structure of the decoder, we use a two-layer transformer for the feature decoder and an 8-layer transformer for the pixel decoder. For the output of the feature decoder, we use the features of all tokens to participate in average pooling, which is the same as the operation of the target encoder part.

**Comment by HuangChiEn** [comment]
> Thank you for your attention. For the structure of the decoder, we use a two-layer transformer for the feature decoder and an 8-layer transformer for the pixel decoder. For the output of the feature decoder, we use the features of all tokens to participate in average pooling, which is the same as the operation of the target encoder part.

Thanks for your reply ~ it's useful information!!
Although we encounter some air turbulence during the pertaining, seems the decoder structure have the wrong settings.

**Comment by HuangChiEn** [comment]
Sorry, forgot to ask that " **all tokens** to participate in average pooling " you mentioned, Is **all tokens** also include the [CLS] token ?

> Thank you for your attention. For the structure of the decoder, we use a two-layer transformer for the feature decoder and an 8-layer transformer for the pixel decoder. For the output of the feature decoder, we use the features of all tokens to participate in average pooling, which is the same as the operation of the target encoder part.

**Comment by ZhichengHuang** [comment]
We only use all tokens from an image, and the CLS token is not used.

**Comment by HuangChiEn** [comment]
> We only use all tokens from an image, and the CLS token is not used.

Thanks for your reply!!

**Comment by HuangChiEn** [comment]
> We only use all tokens from an image, and the CLS token is not used.

Thanks for your reply!!
