### ISSUE TITLE
About more detail of Data Augmentation in CMAE

### ISSUE THREAD

**Issue by HuangChiEn** [ZhichengHuang/CMAE#7]
Thanks for clearify the previous issuese one by one.
Recently, we found one more issue about the DA, would you mind to tell us what's Data Augmentation setup in CMAE? 

We know that you applied all general DA setup in target branch (exactly same as SimCLR). But not sure about the student branch, will you apply the spatial DA, including RandomResize Crop, rotation, or the other ? 
About the Resize crop setup, is that be radom one or center zoomin Crop? 

Any suggestiin will be appreciated!!

**Comment by ZhichengHuang** [comment]
The data augmentation used in the model is discussed in section 3.2 of our paper. For the online branch, we used pixel shift to generate one of the views and then used random flip afterward, which is consistent with MAE. For the target branch, we applied RandomAppliedTrans, RandomGrayscale, and GaussianBlur data enhancements based on the views generated by pixel shift.

**Comment by HuangChiEn** [comment]
> 

Oh.. thanks for your information
> i think i miss to read that part...orz
